site_name: unraphael
site_url: https://unraphaul.readthedocs.io
repo_url: https://github.com/DecodingRaphael/unraphael
repo_name: GitHub

nav:
  - Home: index.md  
  - ðŸ”— Source code: https://github.com/DecodingRaphael/unraphael
  - ðŸ”— Issues: https://github.com/DecodingRaphael/unraphael/issues
  - Getting Started: 
    - Installation: Started/INSTALLATION.md
    - Usage: Started/USAGE.md
    - Tutorials: Started/TUTORIALS.md
    - Known issues: Started/ISSUES.md    
  - Image Processing Steps: 
    - Introduction: Processing/INTRODUCTION.md
    - Preprocessing: Processing/PREPROCESSING.md
    - Segmentation: Processing/SEGMENTATION.md
    - Alignment: Processing/ALIGNMENT.md
    - Clustering: Processing/CLUSTERING.md
  - Developers: 
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Building from source: Developers/SOURCE.md    
    - Contributing guidelines: CONTRIBUTING.md
    - Changelog: Developers/CHANGELOG.md
  - About: 
    - How to Cite: About/CITE.md
    - Contact information: About/CONTACT.md
    - In action: About/ACTION.md
    - FAQ's: About/FAQS.md

theme:
  name: readthedocs
  color_mode: dark
  palette:
    scheme: default
    primary: deep purple
    accent: purple

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
      base_path: docs
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      # https://mkdocstrings.github.io/usage/
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://docs.scipy.org/doc/scipy/objects.inv
          - https://pandas.pydata.org/docs/objects.inv
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: yes
            show_submodules: no
            show_source: true
            docstring_section_style: list
            members_order: alphabetical
            show_category_heading: no
            merge_init_into_class: yes

watch:
  - src/unraphael
  - docs/
